/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0f5238',
        'on-primary': '#ffffff',
        'primary-container': '#2d6a4f',
        'on-primary-container': '#a8e7c5',
        'primary-fixed': '#b1f0ce',
        'primary-fixed-dim': '#95d4b3',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#0e5138',
        'inverse-primary': '#95d4b3',
        secondary: '#75584d',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed7ca',
        'on-secondary-container': '#795c51',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#e4beb2',
        'on-secondary-fixed': '#2b160f',
        'on-secondary-fixed-variant': '#5b4137',
        tertiary: '#005236',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006d48',
        'on-tertiary-container': '#89edba',
        'tertiary-fixed': '#92f7c3',
        'tertiary-fixed-dim': '#75daa8',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005235',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#404943',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#707973',
        'outline-variant': '#bfc9c1',
        'surface-tint': '#2c694e',
        'surface-variant': '#e1e3e4',
        background: '#f8f9fa',
        'on-background': '#191c1d',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'card-gap': '24px',
        'container-padding': '40px',
        'section-margin': '64px',
        'max-width': '1440px',
      },
    },
  },
  plugins: [],
}
